version: '3.4'
services:
  api-gate:
    build:
      context: .
      target: prod
    ports:
      - 8080:8080
  test:
    # image: bash:4
    # command: ["sh", "-c", "sleep 30 && wget -qO- api-gate:8080/demo?name=docker-compose-is-alive"]
    build:
      context: .
      target: test
    environment:
      APIGATE_HOST: 'api-gate'
      APIGATE_PORT: 8080
    depends_on:
      - api-gate
