version: '3'
services:
  api-gate:
    build: .
    ports:
      - 8080:8080
  test:
    image: openjdk:8-jdk-alpine
    command: ["sh", "-c", "sleep 30 && wget -qO- api-gate:8080/healthz?name=docker-compose-is-alive"]
    depends_on:
      - api-gate
